// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnoUJOZ4E7G9p5PTszO9FinxZpABExHUU',
    appId: '1:248896277921:ios:acb21e24ce8ccb1bbe0fe0',
    messagingSenderId: '248896277921',
    projectId: 'realtime-chat-app-5b7d1',
    storageBucket: 'realtime-chat-app-5b7d1.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnoUJOZ4E7G9p5PTszO9FinxZpABExHUU',
    appId: '1:248896277921:ios:acb21e24ce8ccb1bbe0fe0',
    messagingSenderId: '248896277921',
    projectId: 'realtime-chat-app-5b7d1',
    storageBucket: 'realtime-chat-app-5b7d1.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACCKhNPtHkzcmj8ZLVBF0JZO-efd94mGU',
    appId: '1:248896277921:web:b6e401a14faffd8ebe0fe0',
    messagingSenderId: '248896277921',
    projectId: 'realtime-chat-app-5b7d1',
    authDomain: 'realtime-chat-app-5b7d1.firebaseapp.com',
    storageBucket: 'realtime-chat-app-5b7d1.firebasestorage.app',
  );
}
